version: '3.9'

services: 
    db:
        image: postgres
        volumes: 
            - ./data/db:/var/lib/postgresql/data
            - ./import:/home/import
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports: 
            - "5432:5432"
